#!/bin/bash
# DNS Configuration Script for Venture Vision Ubuntu
# Add these A records to your domain registrar

echo "🌐 DNS Configuration for Venture Vision Ubuntu"
echo "=============================================="
echo ""
echo "Go to your domain registrar's DNS management panel and add these A records:"
echo ""
echo "For venturevisionubuntu.co.za:"
echo "  Type: A"
echo "  Name: @ (or leave blank)"
echo "  Value: 76.76.21.21"
echo "  TTL: 300 (5 minutes)"
echo ""
echo "For api.venturevisionubuntu.co.za:"
echo "  Type: A"
echo "  Name: api"
echo "  Value: 76.76.21.21"
echo "  TTL: 300 (5 minutes)"
echo ""
echo "After adding records, wait 5-15 minutes for propagation."
echo ""
echo "Test with:"
echo "  curl https://venturevisionubuntu.co.za"
echo "  curl https://api.venturevisionubuntu.co.za/health"
echo ""
echo "Current temporary URLs:"
echo "  Dashboard: https://dashboard-eta-one-54.vercel.app"
echo "  API: [Check Vercel dashboard for API URL]"
echo ""
echo "✅ Once DNS propagates, your custom domains will be live!"